# Generated by Django 2.2 on 2021-09-24 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='last_name')),
                ('business_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='business_catergory')),
                ('trading_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='trading_name')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mer_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
