# Generated by Django 2.2 on 2021-10-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrIdentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
    ]
