# Generated by Django 2.2 on 2021-11-21 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ocrIdentification', '0002_template_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=1000, null=True, verbose_name='ans_string')),
                ('template', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='temp_mer', to='ocrIdentification.Template')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ans_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
