# Generated by Django 2.2 on 2021-11-21 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocrIdentification', '0003_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='ans_string',
        ),
    ]
