# Generated by Django 2.2 on 2021-11-22 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='email address')),
                ('phone_no', models.CharField(max_length=15, null=True, unique=True, verbose_name='phone number')),
                ('last_login', models.CharField(max_length=100, null=True, unique=True, verbose_name='last login')),
                ('date_joined', models.CharField(max_length=200, null=True, verbose_name='date_joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='active')),
                ('is_merchant', models.BooleanField(default=False, verbose_name='is_merchant')),
                ('is_user', models.BooleanField(default=False, verbose_name='is_user')),
                ('login_attempts', models.CharField(blank=True, max_length=30, null=True, verbose_name='login_attempts')),
                ('is_delete', models.BooleanField(default=False, verbose_name='is_delete')),
                ('delete_on', models.CharField(blank=True, max_length=200, null=True, verbose_name='delete_on')),
                ('reset_token', models.CharField(blank=True, max_length=200, null=True, verbose_name='reset_token')),
                ('reset_token_expire_date', models.CharField(blank=True, max_length=200, null=True, verbose_name='reset_token_expire_date')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.CharField(blank=True, max_length=200, null=True, verbose_name='create_on')),
                ('password', models.CharField(blank=True, max_length=250, null=True, verbose_name='password')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_password_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
